### ISSUE TITLE
Add Terror Zone details

### ISSUE THREAD

**Issue by shupershuff** [rbaron/d2r-tracker-ha-custom-component#17]
Would you also be able to add Current and Next Terror Zone details?

I've found these to be the best sources:

Current TZ: https://d2rapi.fly.dev/
Next TZ: https://thegodofpumpkin.com/terrorzones/terrorzone.png (needs OCR to convert to text, I've been using ocr.space API for another project)

**Comment by rbaron** [comment]
Current TZ tracking is implemented with d2runewizard.com. I'm happy to review a PR if you want to onboard those extra platforms.
